### ISSUE TITLE
Windows CI failing since 2023/11/15

### ISSUE THREAD

**Issue by traversaro** [ami-iit/onnx-cpp-benchmark#12]
Last successful build: https://github.com/ami-iit/onnx-cpp-benchmark/actions/runs/6858310310/job/18648845494 
First failing build: https://github.com/ami-iit/onnx-cpp-benchmark/actions/runs/6872051989/job/18698893038

It fails with:
~~~
D:\a\_temp\c4468d0a-44bf-4f2e-9a4b-9e12273e9b6d.sh: line 2: pixi: command not found
D:\a\_temp\c4468d0a-44bf-4f2e-9a4b-9e12273e9b6d.sh: line 4: pixi: command not found
D:\a\_temp\c4468d0a-44bf-4f2e-9a4b-9e12273e9b6d.sh: line 5: pixi: command not found
~~~

Perhaps something changed recently in the install script? The latest modification seem https://github.com/prefix-dev/pixi/pull/449 by @ruben-arts, but I could not find anything wrong there.

**Comment by ruben-arts** [comment]
This is indeed moved in that pr. I'm not sure why you needed this line:
https://github.com/ami-iit/onnx-cpp-benchmark/blob/5eddb0717b3ca1e5139af4e0089d656dc69bf9c9/.github/workflows/ci.yml#L37

But that should now link `$Env:USERPROFILE\.pixi\bin` to that github path I guess. 
The script should add it to the `$PATH` variable,  is that different from the `GITHUB_PATH`?

**Comment by traversaro** [comment]
Thanks @ruben-arts, and sorry for the noise, I completely forgot that part. Indeed, GitHub Actions modification to the PATH are not propagated between different steps, and the `.bashrc` or similar is not reloaded for new steps. So that is the reason for the workaround. However, at this point I can just switch to use the setup-pixi action.

**Comment by traversaro** [comment]
Fixed by https://github.com/ami-iit/onnx-cpp-benchmark/pull/13 .
